name: blooddonation-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: 'Fazendo checkout no branch'
        uses: actions/checkout@v3
      - name: 'Fazendo setup do Java 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Executando limpeza, testes e build'
        run: mvn clean test package