name: master-workflow
on:
  pull_request:
    branches:
      - master
    types: [ closed ]
jobs:
  generate-prod-build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Fazendo checkout no branch'
        uses: actions/checkout@v3
      - name: 'Fazendo setup do Java 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Executando limpeza, testes e versão para produção'
        run: mvn clean test package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: /app/
          push: true
          tags: cristian486/blooddonation:latest